# Artemis woring directoriy path
ART_ANALYSIS_DIR="./work/training"

# Empty = do not create rawdata symlink
ART_DATA_DIR=""

# Empty = do not create output symlink
ART_OUTPUT_DIR=""

# Repository infomation
REPO_TYPE="github"
REPO_PROTOCOL="https"

REPO_OWNER="FumiHubCNS"
REPO_NAME="artemis-workdir-training"
REPO_BRANCH=""

# Environment for SSH
# SSH_HOST="github.com"
